### ISSUE TITLE
Comment doesn't make sense 

### ISSUE THREAD

**Issue by jvmatl** [FreeRTOS/backoffAlgorithm#26]
https://github.com/FreeRTOS/backoffAlgorithm/blob/741697917a5b9264cd5c11e54e23ce3fe3472636/source/backoff_algorithm.c#L47

Since BACKOFF_ALGORITHM_RETRY_FOREVER is a constant 0, I suspect you meant to say `if maxRetryAttempts == 0 ...`

**Comment by aggarw13** [comment]
Hi @jvmtl, thanks for pointing out the issue with the comment. We will fix the comment soon 🙂.

**Comment by jvmatl** [comment]
Closing this, since it appears the issue is/will-be resolved by the most recent approved PR for #27
